#include "mbootcore/domain/Error.hpp"

namespace mbootcore {

const char* toString(ErrorCode code) noexcept {
    switch (code) {
        case ErrorCode::Success:                  return "Success";
        case ErrorCode::Unknown:                  return "Unknown error";
        case ErrorCode::NotSupported:             return "Operation not supported";
        case ErrorCode::InvalidArgument:          return "Invalid argument";
        case ErrorCode::AlreadyExists:            return "Already exists";
        case ErrorCode::Cancelled:                return "Operation cancelled";
        case ErrorCode::TransportError:           return "Transport error";
        case ErrorCode::TransportTimeout:         return "Transport timeout";
        case ErrorCode::TransportDisconnected:    return "Transport disconnected";
        case ErrorCode::TransportWriteFailed:     return "Transport write failed";
        case ErrorCode::TransportReadFailed:      return "Transport read failed";
        case ErrorCode::ProtocolError:            return "Protocol error";
        case ErrorCode::ProtocolMismatch:         return "Protocol version mismatch";
        case ErrorCode::InvalidPacket:            return "Invalid packet";
        case ErrorCode::UnexpectedPacket:         return "Unexpected packet";
        case ErrorCode::InvalidState:             return "Invalid state for this operation";
        case ErrorCode::UnsupportedVersion:       return "Unsupported protocol version";
        case ErrorCode::SaharaNakSuccess:             return "Sahara: success";
        case ErrorCode::SaharaNakInvalidCmd:          return "Sahara: invalid command";
        case ErrorCode::SaharaNakProtocolMismatch:    return "Sahara: protocol mismatch";
        case ErrorCode::SaharaNakInvalidTargetProto:  return "Sahara: invalid target protocol";
        case ErrorCode::SaharaNakInvalidHostProto:    return "Sahara: invalid host protocol";
        case ErrorCode::SaharaNakInvalidPktSize:      return "Sahara: invalid packet size";
        case ErrorCode::SaharaNakUnexpectedPkt:       return "Sahara: unexpected packet";
        case ErrorCode::SaharaNakInvalidTransferMode: return "Sahara: invalid transfer mode";
        case ErrorCode::SaharaNakInvalidHostId:       return "Sahara: invalid host ID";
        case ErrorCode::SaharaNakTimeoutRx:           return "Sahara: receive timeout";
        case ErrorCode::SaharaNakTimeoutTx:           return "Sahara: transmit timeout";
        case ErrorCode::SaharaNakInvalidMode:         return "Sahara: invalid mode";
        case ErrorCode::SaharaNakInvalidHostReq:      return "Sahara: invalid host request";
        case ErrorCode::SaharaNakReadDataError:       return "Sahara: read data error";
        case ErrorCode::SaharaNakWriteDataError:      return "Sahara: write data error";
        case ErrorCode::SaharaNakInvalidMemTable:     return "Sahara: invalid memory table";
        case ErrorCode::SaharaNakInvalidMemInfo:      return "Sahara: invalid memory info";
        case ErrorCode::SaharaNakMemDebugNotSup:      return "Sahara: memory debug not supported";
        case ErrorCode::SaharaNakMemReadFailed:       return "Sahara: memory read failed";
        case ErrorCode::SaharaNakInvalidImgId:        return "Sahara: invalid image ID";
        case ErrorCode::SaharaNakImgNotFound:         return "Sahara: image not found";
        case ErrorCode::SaharaNakImgAuthFailed:       return "Sahara: image authentication failed";
        case ErrorCode::SaharaNakImgTooLarge:         return "Sahara: image too large";
        case ErrorCode::SaharaNakAuthFailed:          return "Sahara: authentication failed";
        case ErrorCode::SaharaNakInvalidImgHdr:       return "Sahara: invalid image header";
        case ErrorCode::SaharaNakImgHdrInvalidVer:    return "Sahara: invalid image header version";
        case ErrorCode::SaharaNakInvalidSignature:    return "Sahara: invalid signature";
        case ErrorCode::SaharaNakInvalidHash:         return "Sahara: invalid hash";
        case ErrorCode::SaharaNakFatal:               return "Sahara: fatal error";
        case ErrorCode::SaharaNakCmdExecFailure:      return "Sahara: command execution failure";
        case ErrorCode::SaharaNakImgEncFailed:        return "Sahara: image decryption failed";
        case ErrorCode::SaharaNakImgHdrAuthFailed:    return "Sahara: image header auth failed";
        case ErrorCode::SaharaNakImgHdrVerFailed:     return "Sahara: image header version failed";
        case ErrorCode::SaharaNakImgHdrMacFailed:     return "Sahara: image header MAC failed";
        case ErrorCode::SaharaNakImgHdrMacNotFound:   return "Sahara: image header MAC not found";
        case ErrorCode::SaharaNakImgHdrSignFailed:    return "Sahara: image header signature failed";
        case ErrorCode::SaharaNakImgHdrSignNotFound:  return "Sahara: image header signature not found";
        case ErrorCode::SaharaNakInvalidImgContent:   return "Sahara: invalid image content";
        case ErrorCode::SaharaNakInvalidProgrammer:   return "Sahara: invalid programmer";
        case ErrorCode::SaharaNakProgrammerAuthFail:  return "Sahara: programmer auth failed";
        case ErrorCode::SaharaNakProgrammerMismatch:  return "Sahara: programmer mismatch";
        case ErrorCode::LoaderNotFound:           return "Loader not found";
        case ErrorCode::LoaderRejected:           return "Loader rejected by device";
        case ErrorCode::LoaderInvalidFormat:      return "Invalid loader format";
        case ErrorCode::LoaderVersionMismatch:    return "Loader version mismatch";
        case ErrorCode::InvalidElf:               return "Invalid ELF file";
        case ErrorCode::CacheMiss:                return "Cache miss";
        case ErrorCode::DeviceNotFound:           return "Device not found";
        case ErrorCode::DeviceDisconnected:       return "Device disconnected";
        case ErrorCode::DeviceAccessDenied:       return "Device access denied";
        case ErrorCode::ElfSegmentOverlap:        return "ELF overlapping segments";
        case ErrorCode::ElfTruncated:             return "ELF file truncated";
        case ErrorCode::ElfUnsupportedMachine:    return "ELF unsupported machine type";
        case ErrorCode::FirehoseNak:               return "Firehose NAK";
        case ErrorCode::FirehoseSectorOutOfRange:  return "Firehose: sector out of range";
        case ErrorCode::FirehoseProgramFailed:     return "Firehose: program failed";
        case ErrorCode::FirehoseEraseFailed:       return "Firehose: erase failed";
        case ErrorCode::FirehoseUnsupportedMemory: return "Firehose: unsupported memory type";
        case ErrorCode::FirehoseInvalidParam:      return "Firehose: invalid parameter";
        case ErrorCode::FirehoseSeqError:          return "Firehose: command sequence error";
        case ErrorCode::FirehoseTimeout:           return "Firehose: timeout";
        case ErrorCode::FirehoseCrcMismatch:       return "Firehose: CRC mismatch";
        case ErrorCode::FirehosePartialWrite:      return "Firehose: partial write";
        case ErrorCode::GPTCorrupted:              return "GPT table corrupted";
        case ErrorCode::GPTInvalidHeader:          return "GPT invalid header";
        case ErrorCode::GPTInvalidEntry:           return "GPT invalid partition entry";
        case ErrorCode::GPTPrimaryMissing:         return "GPT primary table missing";
        case ErrorCode::GPTBackupMissing:          return "GPT backup table missing";
        case ErrorCode::GPTCrcMismatch:            return "GPT CRC mismatch";
        case ErrorCode::PartitionNotFound:         return "Partition not found";
        case ErrorCode::PartitionOverlap:          return "Partition overlap detected";
        case ErrorCode::InvalidImage:              return "Invalid image file";
        case ErrorCode::ImageTooLarge:             return "Image too large for partition";
        case ErrorCode::DeviceNotIdentified:       return "Device could not be identified";
        case ErrorCode::NegotiationFailed:         return "Protocol negotiation failed";
        case ErrorCode::NoMatchingProtocol:        return "No matching protocol found";
        case ErrorCode::EnumerationFailed:         return "Device enumeration failed";
        case ErrorCode::ProbeFailed:               return "Device probe failed";
        case ErrorCode::DetectorConflict:          return "Detector conflict detected";
        case ErrorCode::RegistryEmpty:             return "Protocol registry is empty";
        case ErrorCode::SessionNotConnected:       return "Session not connected";
        case ErrorCode::SessionAlreadyConnected:   return "Session already connected";
        case ErrorCode::SessionBusy:               return "Session is busy";
        case ErrorCode::SessionTimeout:            return "Session timeout";
        case ErrorCode::SessionTerminal:           return "Session is in terminal state";
        case ErrorCode::SessionLimitExceeded:      return "Session limit exceeded";
        case ErrorCode::PluginLoadFailed:           return "Plugin load failed";
        case ErrorCode::PluginInitFailed:           return "Plugin initialization failed";
        case ErrorCode::PluginShutdownFailed:       return "Plugin shutdown failed";
        case ErrorCode::PluginNotFound:             return "Plugin not found";
        case ErrorCode::PluginIncompatible:         return "Plugin incompatible";
        case ErrorCode::PluginDependencyMissing:    return "Plugin dependency missing";
        case ErrorCode::PluginCircularDependency:   return "Plugin circular dependency";
        case ErrorCode::PluginDuplicate:            return "Plugin duplicate";
        case ErrorCode::PluginAlreadyLoaded:        return "Plugin already loaded";
        case ErrorCode::PluginNotLoaded:            return "Plugin not loaded";
        case ErrorCode::PluginRegistrationFailed:   return "Plugin registration failed";
        case ErrorCode::PluginUnregistrationFailed: return "Plugin unregistration failed";
        case ErrorCode::PluginVersionMismatch:      return "Plugin version mismatch";
        case ErrorCode::PluginConfigInvalid:        return "Plugin config invalid";
        case ErrorCode::JobFailed:                 return "Job execution failed";
        case ErrorCode::JobCancelled:              return "Job cancelled";
        case ErrorCode::JobTimeout:                return "Job timeout";
        case ErrorCode::JobInvalidState:           return "Job in invalid state";
        case ErrorCode::JobDependencyFailed:       return "Job dependency failed";
        case ErrorCode::JobNotFound:               return "Job not found";
        case ErrorCode::JobAlreadyRunning:         return "Job already running";
        case ErrorCode::JobQueueFull:              return "Job queue full";
        case ErrorCode::JobRecoveryFailed:         return "Job recovery failed";
        case ErrorCode::JobRollbackFailed:         return "Job rollback failed";
        case ErrorCode::JobInvalidConfig:          return "Job invalid configuration";
        case ErrorCode::JobDeviceNotReady:         return "Job device not ready";
        case ErrorCode::JobDataMismatch:           return "Job data mismatch";
        case ErrorCode::JobInsufficientSpace:      return "Job insufficient space";
        case ErrorCode::FirmwareInvalidFormat:     return "Firmware: invalid format";
        case ErrorCode::FirmwareImageNotFound:     return "Firmware: image not found";
        case ErrorCode::FirmwareHashMismatch:      return "Firmware: hash mismatch";
        case ErrorCode::FirmwareInvalidManifest:   return "Firmware: invalid manifest";
        case ErrorCode::FirmwareDependencyConflict: return "Firmware: dependency conflict";
        case ErrorCode::FirmwareUnsupportedDevice: return "Firmware: unsupported device";
        case ErrorCode::FirmwareUnsupportedVendor: return "Firmware: unsupported vendor";
        case ErrorCode::FirmwareUnsupportedStorage: return "Firmware: unsupported storage";
        case ErrorCode::FirmwareDuplicatePartition: return "Firmware: duplicate partition";
        case ErrorCode::FirmwareMissingProgrammer: return "Firmware: missing programmer";
        case ErrorCode::FirmwareValidationFailed:  return "Firmware: validation failed";
        case ErrorCode::FirmwareExtractionFailed:  return "Firmware: extraction failed";
        case ErrorCode::FirmwarePackageCorrupted:  return "Firmware: package corrupted";
        case ErrorCode::FirmwareVersionMismatch:   return "Firmware: version mismatch";
        case ErrorCode::FirmwarePackageNotFound:   return "Firmware: package not found";
        case ErrorCode::FirmwareNotEnoughImages:   return "Firmware: not enough images";
        case ErrorCode::WorkflowInvalidState:       return "Workflow: invalid state";
        case ErrorCode::WorkflowStepFailed:         return "Workflow: step failed";
        case ErrorCode::WorkflowRollbackFailed:     return "Workflow: rollback failed";
        case ErrorCode::WorkflowCancelled:          return "Workflow: cancelled";
        case ErrorCode::WorkflowTimeout:            return "Workflow: timeout";
        case ErrorCode::WorkflowStepNotFound:       return "Workflow: step not found";
        case ErrorCode::WorkflowExecutionFailed:    return "Workflow: execution failed";
        case ErrorCode::WorkflowRecoveryFailed:     return "Workflow: recovery failed";
        case ErrorCode::TransportNotOpen:            return "Transport: not open";
        case ErrorCode::TransportAlreadyOpen:        return "Transport: already open";
        case ErrorCode::TransportBusy:               return "Transport: busy";
        case ErrorCode::TransportInvalidEndpoint:    return "Transport: invalid endpoint";
        case ErrorCode::TransportBufferFull:         return "Transport: buffer full";
        case ErrorCode::TransportPartialTransfer:    return "Transport: partial transfer";
        case ErrorCode::TransportReconnectFailed:    return "Transport: reconnect failed";
        case ErrorCode::TransportHotplugRemoved:     return "Transport: hotplug removed";
        case ErrorCode::TransportHotplugArrived:     return "Transport: hotplug arrived";
        case ErrorCode::TransportEnumerationFailed:  return "Transport: enumeration failed";
        case ErrorCode::TransportBackendUnavailable: return "Transport: backend unavailable";
        case ErrorCode::TransportAsyncCancelled:     return "Transport: async cancelled";
        case ErrorCode::TransportRetryExhausted:     return "Transport: retry exhausted";
        case ErrorCode::TransportBufferTooSmall:     return "Transport: buffer too small";
        case ErrorCode::CryptoInitializationFailed:  return "Crypto: initialization failed";
        case ErrorCode::CryptoHashFailed:            return "Crypto: hash computation failed";
        case ErrorCode::CryptoSignatureVerifyFailed: return "Crypto: signature verification failed";
        case ErrorCode::CryptoKeyLoadFailed:         return "Crypto: key loading failed";
        case ErrorCode::CryptoInvalidPadding:        return "Crypto: invalid padding";
        case ErrorCode::CryptoVerificationFailed:    return "Crypto: verification failed";
    }
    return "Unknown error code";
}

} // namespace mbootcore
