# ==========================================================================
# MonolithicArchive.cmake
# --------------------------------------------------------------------------
# Cross-platform archive merging for monolithic static library builds.
#
# Provides mbootcore_create_monolithic_archive() which merges the object
# files from dependency static libraries into the target archive, producing
# a single self-contained static library.
#
# Usage:
#   mbootcore_create_monolithic_archive(mbootcore zlibstatic tfpsacrypto usb-1.0)
#
# Platform tools:
#   MSVC:     lib.exe /OUT: (CMAKE_AR or lib.exe auto-detected)
#   macOS:    libtool -static
#   Linux:    ar x + ar qS + ranlib (each dep extracted to separate dir)
#   MinGW:    ar x + ar qS + ranlib (same as Linux)
# ==========================================================================

include_guard(GLOBAL)

function(mbootcore_create_monolithic_archive TARGET)
    if(NOT TARGET ${TARGET})
        message(FATAL_ERROR
            "mbootcore_create_monolithic_archive: '${TARGET}' is not a target"
        )
    endif()

    # Collect real target names from ARGN (skip empty entries)
    set(_dep_names "")
    foreach(_dep IN LISTS ARGN)
        if(TARGET ${_dep})
            list(APPEND _dep_names "${_dep}")
        endif()
    endforeach()

    if(NOT _dep_names)
        return()
    endif()

    # -------------------------------------------------------------------
    # MSVC: lib.exe /OUT: merges archives natively
    # -------------------------------------------------------------------
    if(MSVC)
        # Find the MSVC librarian.
        # Prefer CMAKE_AR when provided by the active toolchain.
        # CMAKE_LIBTOOL is retained as a manual override for non-standard
        # environments. find_program() is the final fallback.
        set(_lib_tool "")
        if(CMAKE_AR)
            set(_lib_tool "${CMAKE_AR}")
        elseif(CMAKE_LIBTOOL)
            set(_lib_tool "${CMAKE_LIBTOOL}")
        else()
            # Try to locate lib.exe from the Visual Studio environment
            find_program(_msvc_lib NAMES lib lib.exe
                HINTS
                    "$ENV{VCINSTALLDIR}/bin/Hostx64/x64"
                    "$ENV{VCINSTALLDIR}/bin/Hostx86/x86"
                    "$ENV{VCINSTALLDIR}/bin"
            )
            if(_msvc_lib)
                set(_lib_tool "${_msvc_lib}")
            endif()
        endif()

        if(NOT _lib_tool)
            message(FATAL_ERROR
                "mbootcore_create_monolithic_archive: MSVC lib.exe not found. "
                "Set CMAKE_AR or ensure Visual Studio environment is active."
            )
        endif()

        # Build target file list
        set(_dep_files "")
        foreach(_dep IN LISTS _dep_names)
            list(APPEND _dep_files "$<TARGET_FILE:${_dep}>")
        endforeach()

        add_custom_command(TARGET ${TARGET} POST_BUILD
            COMMAND "${_lib_tool}" /NOLOGO
                    /OUT:$<TARGET_FILE:${TARGET}>
                    $<TARGET_FILE:${TARGET}>
                    ${_dep_files}
            COMMENT "Monolithic: merging ${_dep_names} into ${TARGET}"
            VERBATIM
        )
        return()
    endif()

    # -------------------------------------------------------------------
    # macOS: libtool merges static archives natively
    # -------------------------------------------------------------------
    if(APPLE)
        set(_dep_files "")
        foreach(_dep IN LISTS _dep_names)
            list(APPEND _dep_files "$<TARGET_FILE:${_dep}>")
        endforeach()

        add_custom_command(TARGET ${TARGET} POST_BUILD
            COMMAND libtool -static -no_warning_for_no_symbols
                    -o $<TARGET_FILE:${TARGET}>
                    $<TARGET_FILE:${TARGET}>
                    ${_dep_files}
            COMMENT "Monolithic: merging ${_dep_names} into ${TARGET}"
            VERBATIM
        )
        return()
    endif()

    # -------------------------------------------------------------------
    # Linux / MinGW: ar extract + ar append + ranlib
    # -------------------------------------------------------------------
    # Generate a CMake script at configure time with tool paths baked in.
    # Each dependency is extracted into its own subdirectory to avoid
    # object filename collisions (e.g. version.o, error.o, platform.o).
    set(_merge_script "${CMAKE_BINARY_DIR}/monolithic_merge_${TARGET}.cmake")
    file(WRITE "${_merge_script}" "# Auto-generated by MonolithicArchive.cmake — do not edit
cmake_minimum_required(VERSION 3.20)

# Variables are passed via -D flags: ARCHIVE_FILE, ARCHIVE_DEPS, ARCHIVE_AR, ARCHIVE_RANLIB

if(NOT ARCHIVE_FILE OR NOT ARCHIVE_DEPS)
    message(FATAL_ERROR \"Missing ARCHIVE_FILE or ARCHIVE_DEPS arguments\")
endif()

separate_arguments(DEP_FILES UNIX_COMMAND \"\${ARCHIVE_DEPS}\")

set(TMPDIR \"\${CMAKE_BINARY_DIR}/_monolithic_tmp_${TARGET}\")
file(REMOVE_RECURSE \"\${TMPDIR}\")
file(MAKE_DIRECTORY \"\${TMPDIR}\")

# Copy the target archive to work on
file(COPY_FILE \"\${ARCHIVE_FILE}\" \"\${TMPDIR}/merged.a\")

# Extract each dependency archive into its own subdirectory
foreach(DEP_FILE \${DEP_FILES})
    get_filename_component(_dep_name \"\${DEP_FILE}\" NAME_WE)
    set(_dep_dir \"\${TMPDIR}/\${_dep_name}\")
    file(MAKE_DIRECTORY \"\${_dep_dir}\")
    execute_process(
        COMMAND \"\${ARCHIVE_AR}\" x \"\${DEP_FILE}\"
        WORKING_DIRECTORY \"\${_dep_dir}\"
        RESULT_VARIABLE _result
    )
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR \"Failed to extract objects from \${DEP_FILE}\")
    endif()
endforeach()

# Collect all object files from all subdirectories
file(GLOB_RECURSE _all_objects
    LIST_DIRECTORIES false
    \"\${TMPDIR}/*.o\"
    \"\${TMPDIR}/*.obj\"
)

if(NOT _all_objects)
    message(FATAL_ERROR \"No object files found after extraction\")
endif()

# Append all objects to the merged archive
execute_process(
    COMMAND \"\${ARCHIVE_AR}\" qS \"\${TMPDIR}/merged.a\" \${_all_objects}
    RESULT_VARIABLE _result
)
if(NOT _result EQUAL 0)
    message(FATAL_ERROR \"Failed to append objects to merged archive\")
endif()

# Rebuild archive index
if(EXISTS \"\${ARCHIVE_RANLIB}\")
    execute_process(
        COMMAND \"\${ARCHIVE_RANLIB}\" \"\${TMPDIR}/merged.a\"
    )
endif()

# Replace the original archive
file(COPY_FILE \"\${TMPDIR}/merged.a\" \"\${ARCHIVE_FILE}\")

# Cleanup
file(REMOVE_RECURSE \"\${TMPDIR}\")
")

    # Collect file paths for each dependency
    set(_dep_files "")
    foreach(_dep IN LISTS _dep_names)
        list(APPEND _dep_files "$<TARGET_FILE:${_dep}>")
    endforeach()

    # Join file paths with semicolons for the -DDEPS argument
    string(REPLACE ";" " " _dep_files_str "${_dep_files}")

    # Resolve the archiver and ranlib at configure time
    set(_ar_cmd "${CMAKE_AR}")
    set(_ranlib_cmd "${CMAKE_RANLIB}")

    add_custom_command(TARGET ${TARGET} POST_BUILD
        COMMAND ${CMAKE_COMMAND}
                "-DARCHIVE_FILE=$<TARGET_FILE:${TARGET}>"
                "-DARCHIVE_DEPS=${_dep_files_str}"
                "-DARCHIVE_AR=${_ar_cmd}"
                "-DARCHIVE_RANLIB=${_ranlib_cmd}"
                -P "${_merge_script}"
        COMMENT "Monolithic: merging ${_dep_names} into ${TARGET}"
        VERBATIM
    )
endfunction()
